### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by bichopaulinho** [bichopaulinho/PaquetesConClase#8]
Ahí va una propuesta. No son títulos de las diapositivas, sino ideas.
- **C++ en R. ¿Para qué?:** Generalmente 'aceleración' de funciones. Un paso más allá: reutilización de cógido (no reprogramar, evitar programar)
- **Aplicación real:** caso de empresa tecnológica (mencionar Meteo?). Depto de Producción: Implementción y mantenimiento de software operativo. Se busca: rendimiento, estructura, integración contínua, etc --> bibliotecas en C++.
  Depto de I+D: desarrollo y mejora de modelos. Se busca: capacidad de análisis, uso sencillo de la info, representación gráfica, prototipos --> paquete R. Librerías C++ en Paquete R: INTERFAZ
- **Vamos a hacer una interfaz en 10 minutos**: Necesitamos.
  - Librería con objetos de C++ que queremos integrar
  - Función en R que use los objetos anteriores como queremos.
  - Alguien que sepa C++ cerca. La mala noticia: Hay que programar en C++. La buena: tenemos Rcpp
- **Nuestro Caso**
  - Integraremos el algoritmo de optimización 'Gradient Descent' (implementación sencilla: librería Purple) para el problema de regresión lineal múltiple en una función contenida en un paquete (GradDesc)
  - Pasos:
    - Escribimos nuestra función `GradientDescentSumaCuadrados`:
      - Argumentos de entrada: Objetos de R (Matriz y vector) de la clase `Rcpp` o el "nativo" `SEXP`
      - Transformación en objetos `Purple::` (y viceversa). Template specialization de `Rcpp::wrap` y `Rcpp::as`
      - Creación objeto función objetivo, algoritmo de optimización, parámetros optimización, etc
      - Ejecución optimización. Salida: parámetros optimizados (objeto R)
    - Compilación del paquete GradDesc. PREVIAMENTE compilar la librería Purple en estático. ¿Esto es necesario? Sí, si queremos evitar problemas de compatibilidad, concordancia tool-chain, etc. Ejemplo Makefile.
      - Compilación paquete: Build tools de Rstudio. Ejemplo Makevars
- **A probarlo**: determinar qué ejemplo/s enseñamos

**Comment by gonzmg88** [comment]
Me gusta, estoy de acuerdo con la estructura,  yo si diría lo de meteo
